# -*- makefile -*-

# platform dependent files
ARCH = button-sensor.c leds_arch.c leds.c sensors.c

CONTIKI_TARGET_DIRS = . 
ifndef CONTIKI_TARGET_MAIN
CONTIKI_TARGET_MAIN = contiki-main.c 
endif

CONTIKI_TARGET_SOURCEFILES += $(ARCH) $(CONTIKI_TARGET_MAIN)

PLATFORM_DEFINES = \
	HSE_VALUE="8000000" \
	DISCOVERY="1" \
#	USE_SERIAL_LINE_USART3 \
#	WITH_SERIAL_LINE_INPUT_USART3 \

# rf chip
include $(CONTIKI)/cpu/avr/radio/rf230bb/Makefile.rf231

MCU=STM32F407
include $(CONTIKI)/cpu/stm32f407/Makefile.stm32f407
