# -*- makefile -*-

# platform dependent files
ARCH = button-sensor.c leds_arch.c leds.c sensors.c

CONTIKI_TARGET_DIRS = . 
ifndef CONTIKI_TARGET_MAIN
CONTIKI_TARGET_MAIN = contiki-main.c 
endif

# rf chip
include $(CONTIKI)/cpu/avr/radio/rf230bb/Makefile.rf231

CONTIKI_TARGET_SOURCEFILES += $(ARCH) $(CONTIKI_TARGET_MAIN)

PLATFORM_DEFINES = \
	HSE_VALUE="8000000" \
	DISCOVERY="1" \
	USE_USART3 \
	USART3_INPUT \
	STDOUT_LINE=3 \
	STDIN_LINE=3 \
	STDERR_LINE=3 \
	USART3_TX_USE_DMA1_CH4 \
#	USE_USB \


MCU=STM32F407
include $(CONTIKI)/cpu/stm32f407/Makefile.stm32f407
