# -*- makefile -*-

# platform dependent files
ARCH = button-sensor.c leds_arch.c

CONTIKI_TARGET_DIRS = . 
ifndef CONTIKI_TARGET_MAIN
CONTIKI_TARGET_MAIN = contiki-main.c 
endif

CONTIKI_TARGET_SOURCEFILES += $(ARCH) $(CONTIKI_TARGET_MAIN)


MCU=STM32F407
include $(CONTIKI)/cpu/stm32f407/Makefile.stm32f407

# rf chip
include $(CONTIKI)/cpu/avr/radio/rf230bb/Makefile.rf230bb
