# -*- makefile -*-

CONTIKI_PROJECT = udpPlug
all: $(CONTIKI_PROJECT)

UIP_CONF_IPV6=1
UIP_CONF_IPV6_RPL=1

PROJECT_DEFINES = \
	AUTOSTART_ENABLE \

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
